apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roundz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ramucaru/rounds-enterprise
    targetRevision: main
    path: Roundz/Infrastructure/helm
  destination:
    server: https://kubernetes.default.svc
    namespace: roundz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
