FROM node:22-alpine AS base
WORKDIR /app
COPY package*.json ./
COPY Roundz/package*.json ./Roundz/
COPY Roundz/Shared ./Roundz/Shared
COPY Roundz/Server ./Roundz/Server
WORKDIR /app/Roundz
RUN npm install && npm run build:shared && npm run build:server
CMD ["node", "Server/gateway/dist/index.js"]
