FROM node:22-alpine AS base
WORKDIR /app
COPY Roundz/package*.json ./
COPY Roundz/Server ./Server
RUN npm ci --workspaces --include-workspace-root
RUN npm run build:server
CMD ["node", "Server/gateway/dist/index.js"]
